name: EmailStepTest

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f1001717@ds.study.iitm.ac.in
        run: echo "Hello, world!"
